# Generated by Django 5.0.3 on 2024-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intrest',
        ),
        migrations.AddField(
            model_name='profile',
            name='intrest',
            field=models.ManyToManyField(choices=[('Music', 'Music'), ('Movies and TV Shows', 'Movies and TV Shows'), ('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Fashion and Beauty', 'Fashion and Beauty'), ('Technology and Gadgets', 'Technology and Gadgets'), ('Travel and Adventure', 'Travel and Adventure'), ('Fitness and Wellness', 'Fitness and Wellness'), ('Art and Creativity', 'Art and Creativity'), ('Social Causes and Activism', 'Social Causes and Activism')], default='', to='social_app.interest'),
        ),
    ]
