# Generated by Django 5.0.3 on 2024-04-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_rename_intrest_profile_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
