# Generated by Django 5.0.3 on 2024-04-05 05:33

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_alter_interest_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_img', models.ImageField(upload_to='Posts_images')),
                ('caption', models.TextField()),
                ('no_of_likes', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.datetime(2024, 4, 5, 11, 3, 12, 662102))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
