# Generated by Django 5.0.3 on 2024-04-11 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_likemodel_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('follower', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 4, 11, 11, 32, 21, 710540)),
        ),
    ]
